name: build-dev-package
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.3.1
        with:
          command: ros2 run rosapi
          base-image: rwthika/ros2:humble-ros-core
          ros-distro: humble
          platform: amd64
          image-name: ghcr.io/${{ github.repository }}/humble
      - name: Clean up
        run: |
          docker system prune -a -f